version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./db
        target: /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  twitter:
    image: node
    restart: always
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_TOKEN_KEY:
      TWITTER_TOKEN_SECRET: 
    volumes:
      - type: bind
        source: ./twitter
        target: /home/node/app
    command: node index.js

  title:
    build: ./py
    restart: always
    command: python ./scripts.py
